//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Atlas.Web.UI.asp.global.controls {
    
    
    public partial class bank_add_details {
        
        /// <summary>
        /// mainDiv control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl mainDiv;
        
        /// <summary>
        /// bankCountryCaptionLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.WebForm.Label bankCountryCaptionLabel;
        
        /// <summary>
        /// bankCountryNameDDL control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.WebForm.DropDownList bankCountryNameDDL;
        
        /// <summary>
        /// bankCountryNameReqValidator control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.Validation.RequiredFieldValidator bankCountryNameReqValidator;
        
        /// <summary>
        /// disbursementCurrencyLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.WebForm.Label disbursementCurrencyLabel;
        
        /// <summary>
        /// disbursementCurrencyDDL control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.WebForm.DropDownList disbursementCurrencyDDL;
        
        /// <summary>
        /// disbursementCurrencyReqValidator control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.Validation.RequiredFieldValidator disbursementCurrencyReqValidator;
        
        /// <summary>
        /// countryContinueBtn control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.WebForm.Button countryContinueBtn;
        
        /// <summary>
        /// routingNumberLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.WebForm.Label routingNumberLabel;
        
        /// <summary>
        /// routingNumberTxt control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.WebForm.TextBox routingNumberTxt;
        
        /// <summary>
        /// SWIFTBICCodelabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.WebForm.Label SWIFTBICCodelabel;
        
        /// <summary>
        /// SWIFTBICCodeTxt control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.WebForm.TextBox SWIFTBICCodeTxt;
        
        /// <summary>
        /// routingNumberReqValidator control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.Validation.CustomValidator routingNumberReqValidator;
        
        /// <summary>
        /// findBankBtn control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.WebForm.Button findBankBtn;
        
        /// <summary>
        /// bankNotFoundMessageDiv control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl bankNotFoundMessageDiv;
        
        /// <summary>
        /// addressHeaderLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.WebForm.Label addressHeaderLabel;
        
        /// <summary>
        /// addressSupplierLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.WebForm.Label addressSupplierLabel;
        
        /// <summary>
        /// createdByRow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableRow createdByRow;
        
        /// <summary>
        /// createdBylbl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.WebForm.Label createdBylbl;
        
        /// <summary>
        /// createdBylbltxt control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.WebForm.Label createdBylbltxt;
        
        /// <summary>
        /// statusLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.WebForm.Label statusLabel;
        
        /// <summary>
        /// bankStatusDDL control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.WebForm.DropDownList bankStatusDDL;
        
        /// <summary>
        /// bankStatusDDLReqValidator control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.Validation.RequiredFieldValidator bankStatusDDLReqValidator;
        
        /// <summary>
        /// paymentMethdLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.WebForm.Label paymentMethdLabel;
        
        /// <summary>
        /// paymentMethodDDL control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.WebForm.DropDownList paymentMethodDDL;
        
        /// <summary>
        /// paymentMethodDDLReqValidator control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.Validation.RequiredFieldValidator paymentMethodDDLReqValidator;
        
        /// <summary>
        /// payeeBankNameLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.WebForm.Label payeeBankNameLabel;
        
        /// <summary>
        /// payeeBankNameTxt control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.WebForm.TextBox payeeBankNameTxt;
        
        /// <summary>
        /// payeeBankNameTxtReqValidator control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.Validation.RequiredFieldValidator payeeBankNameTxtReqValidator;
        
        /// <summary>
        /// payeeBankNameTxtRegularExpValidator control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.Validation.RegularExpressionValidator payeeBankNameTxtRegularExpValidator;
        
        /// <summary>
        /// bankPhoneLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.WebForm.Label bankPhoneLabel;
        
        /// <summary>
        /// bankPhoneTxt control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.WebForm.TextBox bankPhoneTxt;
        
        /// <summary>
        /// bankPhoneTxtCustomerValidator control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.Validation.CustomValidator bankPhoneTxtCustomerValidator;
        
        /// <summary>
        /// bankPhoneTxtRegexpvalidator control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.Validation.RegularExpressionValidator bankPhoneTxtRegexpvalidator;
        
        /// <summary>
        /// bankAddrCaptionLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.WebForm.Label bankAddrCaptionLabel;
        
        /// <summary>
        /// bankAddressLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.WebForm.Label bankAddressLabel;
        
        /// <summary>
        /// bankCityLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.WebForm.Label bankCityLabel;
        
        /// <summary>
        /// bankStateLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.WebForm.Label bankStateLabel;
        
        /// <summary>
        /// bankPostalCodeLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.WebForm.Label bankPostalCodeLabel;
        
        /// <summary>
        /// bankCountryLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.WebForm.Label bankCountryLabel;
        
        /// <summary>
        /// invalidAddressLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.WebForm.Label invalidAddressLabel;
        
        /// <summary>
        /// bankNewaddrLine1Label control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.WebForm.Label bankNewaddrLine1Label;
        
        /// <summary>
        /// bankNewAddrLine1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.WebForm.TextBox bankNewAddrLine1;
        
        /// <summary>
        /// bankNewAddrLine1ReqValidator control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.Validation.RequiredFieldValidator bankNewAddrLine1ReqValidator;
        
        /// <summary>
        /// bankNewAddrLine1CustomValidator control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.Validation.CustomValidator bankNewAddrLine1CustomValidator;
        
        /// <summary>
        /// bankNewAddrLine1Regexpvalidator control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.Validation.RegularExpressionValidator bankNewAddrLine1Regexpvalidator;
        
        /// <summary>
        /// bankNewAddressCityLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.WebForm.Label bankNewAddressCityLabel;
        
        /// <summary>
        /// bankNewAddrCountryLabel_Supplier control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.WebForm.Label bankNewAddrCountryLabel_Supplier;
        
        /// <summary>
        /// bankNewAddressCityTxt control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.WebForm.TextBox bankNewAddressCityTxt;
        
        /// <summary>
        /// bankNewAddressCountryTxt_Supplier control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.WebForm.TextBox bankNewAddressCountryTxt_Supplier;
        
        /// <summary>
        /// addCountryWidget_Supplier control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.WebForm.Widget addCountryWidget_Supplier;
        
        /// <summary>
        /// bankNewAddressCountryTxtCountryValidator_Supplier control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.Validation.CountryValidator bankNewAddressCountryTxtCountryValidator_Supplier;
        
        /// <summary>
        /// bankNewAddressCountryTxtReqValidator_Supplier control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.Validation.RequiredFieldValidator bankNewAddressCountryTxtReqValidator_Supplier;
        
        /// <summary>
        /// bankNewAddressCityTxtReqValidator control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.Validation.RequiredFieldValidator bankNewAddressCityTxtReqValidator;
        
        /// <summary>
        /// CityRegexpvalidator control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.Validation.RegularExpressionValidator CityRegexpvalidator;
        
        /// <summary>
        /// bankNewAddrLine2Label control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.WebForm.Label bankNewAddrLine2Label;
        
        /// <summary>
        /// bankNewAddrLine2Txt control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.WebForm.TextBox bankNewAddrLine2Txt;
        
        /// <summary>
        /// bankNewAddrLine2TxtRegExpValidator control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.Validation.RegularExpressionValidator bankNewAddrLine2TxtRegExpValidator;
        
        /// <summary>
        /// bankNewAddressStateProvLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.WebForm.Label bankNewAddressStateProvLabel;
        
        /// <summary>
        /// bankNewAddresssStateProvTxt control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.WebForm.TextBox bankNewAddresssStateProvTxt;
        
        /// <summary>
        /// bankNewAddresssStateProvTxtRegExpValidator control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.Validation.RegularExpressionValidator bankNewAddresssStateProvTxtRegExpValidator;
        
        /// <summary>
        /// bankNewAddrLine3Label control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.WebForm.Label bankNewAddrLine3Label;
        
        /// <summary>
        /// bankNewAddrLine3Txt control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.WebForm.TextBox bankNewAddrLine3Txt;
        
        /// <summary>
        /// bankNewAddrLine3TxtRegExpValidator control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.Validation.RegularExpressionValidator bankNewAddrLine3TxtRegExpValidator;
        
        /// <summary>
        /// bankNewAddrCountryLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.WebForm.Label bankNewAddrCountryLabel;
        
        /// <summary>
        /// bankNewAddressCityLabel_Supplier control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.WebForm.Label bankNewAddressCityLabel_Supplier;
        
        /// <summary>
        /// bankNewAddressCountryTxt control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.WebForm.TextBox bankNewAddressCountryTxt;
        
        /// <summary>
        /// addCountryWidget control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.WebForm.Widget addCountryWidget;
        
        /// <summary>
        /// bankNewAddressCountryTxtCountryValidator control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.Validation.CountryValidator bankNewAddressCountryTxtCountryValidator;
        
        /// <summary>
        /// bankNewAddressCountryTxtReqValidator control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.Validation.RequiredFieldValidator bankNewAddressCountryTxtReqValidator;
        
        /// <summary>
        /// bankNewAddressCityTxt_Supplier control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.WebForm.TextBox bankNewAddressCityTxt_Supplier;
        
        /// <summary>
        /// bankNewAddresssStateProvTxtCustomValidator control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.Validation.CustomValidator bankNewAddresssStateProvTxtCustomValidator;
        
        /// <summary>
        /// bankNewAddressCityTxtReqValidator_Supplier control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.Validation.RequiredFieldValidator bankNewAddressCityTxtReqValidator_Supplier;
        
        /// <summary>
        /// CityRegexpvalidator_Supplier control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.Validation.RegularExpressionValidator CityRegexpvalidator_Supplier;
        
        /// <summary>
        /// bankNewAddrPostalCodeLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.WebForm.Label bankNewAddrPostalCodeLabel;
        
        /// <summary>
        /// bankNewAddressPostalCodeTxt control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.WebForm.TextBox bankNewAddressPostalCodeTxt;
        
        /// <summary>
        /// bankNewAddressPostalCodeTxtCustomvalidator control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.Validation.CustomValidator bankNewAddressPostalCodeTxtCustomvalidator;
        
        /// <summary>
        /// USPostalFormatCustomvalidator control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.Validation.CustomValidator USPostalFormatCustomvalidator;
        
        /// <summary>
        /// bankNewAddressPostalCodeTxtRegExpvalidator control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.Validation.RegularExpressionValidator bankNewAddressPostalCodeTxtRegExpvalidator;
        
        /// <summary>
        /// bankAdressCountryCompareValidator control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.Validation.CustomValidator bankAdressCountryCompareValidator;
        
        /// <summary>
        /// CanadianPostalFormatCustomvalidator control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.Validation.CustomValidator CanadianPostalFormatCustomvalidator;
        
        /// <summary>
        /// IBANAccNoLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.WebForm.Label IBANAccNoLabel;
        
        /// <summary>
        /// IBANAccountNumberTxt control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.WebForm.TextBox IBANAccountNumberTxt;
        
        /// <summary>
        /// IBANAccountNumberTxtReqValidator control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.Validation.RequiredFieldValidator IBANAccountNumberTxtReqValidator;
        
        /// <summary>
        /// IBANAccountNumberTxtRegExpValidator control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.Validation.RegularExpressionValidator IBANAccountNumberTxtRegExpValidator;
        
        /// <summary>
        /// reTypeIBANAccNoLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.WebForm.Label reTypeIBANAccNoLabel;
        
        /// <summary>
        /// reTypeIBANAccountNumberTxt control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.WebForm.TextBox reTypeIBANAccountNumberTxt;
        
        /// <summary>
        /// reTypeIBANAccountNumberTxtRegExpValidator control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.Validation.RegularExpressionValidator reTypeIBANAccountNumberTxtRegExpValidator;
        
        /// <summary>
        /// reTypeIBANAccountNumberCustomValidator control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.Validation.CustomValidator reTypeIBANAccountNumberCustomValidator;
        
        /// <summary>
        /// accountHolderLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.WebForm.Label accountHolderLabel;
        
        /// <summary>
        /// accountHolderrowtxt control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell accountHolderrowtxt;
        
        /// <summary>
        /// accountHolderTxt control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.WebForm.TextBox accountHolderTxt;
        
        /// <summary>
        /// accountHolderTxtReqValidator control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.Validation.RequiredFieldValidator accountHolderTxtReqValidator;
        
        /// <summary>
        /// accountHolderTxtRegExpValidator control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.Validation.RegularExpressionValidator accountHolderTxtRegExpValidator;
        
        /// <summary>
        /// bankAddlInfoDiv control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableRow bankAddlInfoDiv;
        
        /// <summary>
        /// accountHolderStaticLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.WebForm.Label accountHolderStaticLabel;
        
        /// <summary>
        /// federalTaxNumRow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableRow federalTaxNumRow;
        
        /// <summary>
        /// federalTaxNum control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell federalTaxNum;
        
        /// <summary>
        /// federalTaxNumLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.WebForm.Label federalTaxNumLabel;
        
        /// <summary>
        /// FederalTaxNUmValue control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell FederalTaxNUmValue;
        
        /// <summary>
        /// federalTaxNumTxt control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.WebForm.TextBox federalTaxNumTxt;
        
        /// <summary>
        /// FederalTaxNumCustomVal control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.Validation.CustomValidator FederalTaxNumCustomVal;
        
        /// <summary>
        /// FederalTaxIdCustomVal control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.Validation.CustomValidator FederalTaxIdCustomVal;
        
        /// <summary>
        /// FederalTaxNumRegexVal control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.Validation.RegularExpressionValidator FederalTaxNumRegexVal;
        
        /// <summary>
        /// FederalTaxIDMaxLengthVal control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.Validation.RegularExpressionValidator FederalTaxIDMaxLengthVal;
        
        /// <summary>
        /// PANTANrow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableRow PANTANrow;
        
        /// <summary>
        /// PANLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.WebForm.Label PANLabel;
        
        /// <summary>
        /// PANspan control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl PANspan;
        
        /// <summary>
        /// PANTextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.WebForm.TextBox PANTextBox;
        
        /// <summary>
        /// PANRegExprValidator control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.Validation.RegularExpressionValidator PANRegExprValidator;
        
        /// <summary>
        /// TANLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.WebForm.Label TANLabel;
        
        /// <summary>
        /// TANspan control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl TANspan;
        
        /// <summary>
        /// TANTextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.WebForm.TextBox TANTextBox;
        
        /// <summary>
        /// TANRegExpValidator control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.Validation.RegularExpressionValidator TANRegExpValidator;
        
        /// <summary>
        /// stateAndCityTaxRow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableRow stateAndCityTaxRow;
        
        /// <summary>
        /// stateTaxIdLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.WebForm.Label stateTaxIdLabel;
        
        /// <summary>
        /// stateTaxIdValue control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell stateTaxIdValue;
        
        /// <summary>
        /// stateTaxIDTxt control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.WebForm.TextBox stateTaxIDTxt;
        
        /// <summary>
        /// StateTaxIDRegExVal control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.Validation.RegularExpressionValidator StateTaxIDRegExVal;
        
        /// <summary>
        /// StateTaxIdMaxLenghtVal control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.Validation.RegularExpressionValidator StateTaxIdMaxLenghtVal;
        
        /// <summary>
        /// CityTaxIDLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.WebForm.Label CityTaxIDLabel;
        
        /// <summary>
        /// CityTaxIdValue control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell CityTaxIdValue;
        
        /// <summary>
        /// CityTaxIDTxt control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.WebForm.TextBox CityTaxIDTxt;
        
        /// <summary>
        /// CityTaxIDRegexVal control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.Validation.RegularExpressionValidator CityTaxIDRegexVal;
        
        /// <summary>
        /// CityTaxIdMaxLenghtVal control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.Validation.RegularExpressionValidator CityTaxIdMaxLenghtVal;
        
        /// <summary>
        /// accountTypeLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.WebForm.Label accountTypeLabel;
        
        /// <summary>
        /// accountTypeDDL control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.WebForm.DropDownList accountTypeDDL;
        
        /// <summary>
        /// accountTypeDDLReqvalidator control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.Validation.RequiredFieldValidator accountTypeDDLReqvalidator;
        
        /// <summary>
        /// accountClassLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.WebForm.Label accountClassLabel;
        
        /// <summary>
        /// accountClassDDL control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.WebForm.DropDownList accountClassDDL;
        
        /// <summary>
        /// accountClassDDLReqvalidator control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.Validation.RequiredFieldValidator accountClassDDLReqvalidator;
        
        /// <summary>
        /// paymentcatLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.WebForm.Label paymentcatLabel;
        
        /// <summary>
        /// paymentCategoryDiv control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl paymentCategoryDiv;
        
        /// <summary>
        /// paymentcategoryCBL control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.WebForm.CheckBoxList paymentcategoryCBL;
        
        /// <summary>
        /// paymentcategoryCBLRequiredFieldValidator control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.Validation.RequiredFieldValidator paymentcategoryCBLRequiredFieldValidator;
        
        /// <summary>
        /// paymentcatdescrLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.WebForm.Label paymentcatdescrLabel;
        
        /// <summary>
        /// paymentcatdescrTxt control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.WebForm.TextBox paymentcatdescrTxt;
        
        /// <summary>
        /// paymentcatdescrTxtRegExpValidator control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.Validation.RegularExpressionValidator paymentcatdescrTxtRegExpValidator;
        
        /// <summary>
        /// paymentcatdescrTxtMaxLengthValidator control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.Validation.RegularExpressionValidator paymentcatdescrTxtMaxLengthValidator;
        
        /// <summary>
        /// globalPayrollCheckLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.WebForm.Label globalPayrollCheckLabel;
        
        /// <summary>
        /// globalPayrollCheck control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.WebForm.CheckBox globalPayrollCheck;
        
        /// <summary>
        /// globalPayrollCheckCustomValidator control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.Validation.CustomValidator globalPayrollCheckCustomValidator;
        
        /// <summary>
        /// payrollNameLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.WebForm.Label payrollNameLabel;
        
        /// <summary>
        /// payrollNameTxt control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.WebForm.TextBox payrollNameTxt;
        
        /// <summary>
        /// countryWidget control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.WebForm.Widget countryWidget;
        
        /// <summary>
        /// payrollNameTxtCountryValidator control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.Validation.CountryValidator payrollNameTxtCountryValidator;
        
        /// <summary>
        /// additionalBankInformationLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.WebForm.Label additionalBankInformationLabel;
        
        /// <summary>
        /// specialInstructionsTxt control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.WebForm.TextBox specialInstructionsTxt;
        
        /// <summary>
        /// specialInstructionsRegExpValidator control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.Validation.RegularExpressionValidator specialInstructionsRegExpValidator;
        
        /// <summary>
        /// specialInstructionsTxtMaxValidator control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.Validation.RegularExpressionValidator specialInstructionsTxtMaxValidator;
        
        /// <summary>
        /// paythroughbankneededlabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.WebForm.Label paythroughbankneededlabel;
        
        /// <summary>
        /// paythroughBankNeededCheck control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.Controls.WebForm.CheckBox paythroughBankNeededCheck;
        
        /// <summary>
        /// paythroughBankTR control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableRow paythroughBankTR;
        
        /// <summary>
        /// payThroughBankUC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.Atlas.Web.UI.asp.global.controls.add_paythrough_bank payThroughBankUC;
        
        /// <summary>
        /// displayRoutingNoDivHidden control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField displayRoutingNoDivHidden;
        
        /// <summary>
        /// displayBankInfoDivHidden control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField displayBankInfoDivHidden;
        
        /// <summary>
        /// bankRoutingTypCdHidden control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField bankRoutingTypCdHidden;
        
        /// <summary>
        /// bankAddressFoundHidden control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField bankAddressFoundHidden;
        
        /// <summary>
        /// errorTextHidden control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField errorTextHidden;
        
        /// <summary>
        /// paythroughbankReqIndHidden control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField paythroughbankReqIndHidden;
        
        /// <summary>
        /// routingNoRequiredIndHidden control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField routingNoRequiredIndHidden;
        
        /// <summary>
        /// isABANumbrvalidHidden control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField isABANumbrvalidHidden;
        
        /// <summary>
        /// isABANumberAlphaHidden control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField isABANumberAlphaHidden;
    }
}
